sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  - TRAVIS_NODE_VERSION="6.11.0"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker stop
  - sudo sed -i "s/ExecStart=\/usr\/bin\/dockerd -H fd:\/\//ExecStart=\/usr\/bin\/dockerd -H fd:\/\/ -H tcp:\/\/0.0.0.0:2375 -H unix:\/\/\/var\/run\/docker.sock/g"  /lib/systemd/system/docker.service
  - sudo service docker start
  - chmod +x gradlew
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g @angular/cli

script:
  - ./gradlew jacocoTestReport --stacktrace
  - cd tci-webapp && npm install
  - npm run build
  - cd ..

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

    docker build -t travelci/tci-database ./tci-database;
    docker push travelci/tci-database;

    docker build -t travelci/tci-config ./tci-config;
    docker push travelci/tci-config;

    docker build -t travelci/tci-eureka:latest ./tci-eureka;
    docker push travelci/tci-eureka;

    docker build -t travelci/tci-gateway:latest ./tci-gateway;
    docker push travelci/tci-gateway;

    docker build -t travelci/tci-webhook:latest ./tci-webhook;
    docker push travelci/tci-webhook;

    docker build -t travelci/tci-projects:latest ./tci-projects;
    docker push travelci/tci-projects;

    docker build -t travelci/tci-commands:latest ./tci-commands;
    docker push travelci/tci-commands;

    docker build -t travelci/tci-docker-runner:latest ./tci-docker-runner;
    docker push travelci/tci-docker-runner;

    docker build -t travelci/tci-logger:latest ./tci-logger;
    docker push travelci/tci-logger;

    docker build -t travelci/tci-notifications:latest ./tci-notifications;
    docker push travelci/tci-notifications;

    docker build -t travelci/tci-webapp:latest ./tci-webapp;
    docker push travelci/tci-webapp;
    fi

notifications:
  slack:
    secure: eY2Id+Oo1TKAKE5EV68Ybt0wlgp8ZVBz+mhRIV7eXiEOnXxMz1jBwIAkmyv/trvQNtAyCSKtvp9sj6VR3sRa4Gldd6EccxrWjA7E7dN1o+1z+taYUn2uEVhlKO5nUb/IKI4nsU78nn8kQPtxkAQErF4PqPpf4LKg6yb/O8a+GsyaqeLrRmihGfNX+vRUMwo8UyspUdoT5f1MHFWZBQpBybyZXCDPp6S/NAA93M8iZ9S3UFquN1HyDVL8Cv0jVWjke9uURCjTxQ28IBI4ecJuXw2wUJumH1Y+wrWhqZ0S5iMgdGIIaePQTd0k5xhD6oPdDA94J9E9Fk4OBwOpfpSqhvArYxYZlIuAnBulhdTFqBKH8ypuRh6R4dT9ljyIZkr+ITZqmGslIBZGeq3i6Sl7NMNtOh9bzr/v2d3Ay5ByF7IdWVMvFUBLm4uWkpiVHSb/F+FH7ULKKjhho611oZr/7rotoKpnWAaNWDp0HJ/X4t95OFfnNmWBD6a2Tv50T9kEWXkzOVuoeSI3PTvUBI/LfJwEGGdh2vAi5rfFEtgdV4SoaZGa7IiFsgmats2q3l0dFeEC92DyWQWDAoVrM6S+LJB8fxrJEiHFucBTbGLgTGRLrLUVwlUw+KBZTTT33neeGIDKVGbaCdrRgYLPiVveQyIPsr/b7UeQLUmph8vKcFc=