image: java:8

pipelines:
  default:
    - step:
        script:
          - bash ./gradlew jacocoTestReport
          - curl --insecure -OL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.8.zip
          - unzip sonar-scanner-2.8.zip
          - ./sonar-scanner-2.8/bin/sonar-scanner