image: java:8

pipelines:
  default:
    - step:
        script:
          - ls -al /run/ | grep docker
          - bash ./gradlew jacocoTestReport --stacktrace --info
          - bash ./gradlew sonarqube

options:
  docker: true