version: '3.7'

networks:
  spring-cloud-network:
  bdd-network:

volumes:
  tci-database-volume:
  tci-projects-volume:

services:
  travelci-database:
    image: travelci/tci-database:latest
    networks:
      - bdd-network
    environment:
      - POSTGRES_DB=travelci
    volumes:
      - tci-database-volume:/var/lib/postgresql/data

  travelci-config:
    image: travelci/tci-config:latest
    networks:
      - spring-cloud-network

  travelci-eureka:
    image: travelci/tci-eureka:latest
    networks:
      - spring-cloud-network
    ports:
      - "${TCI_EUREKA_PORT}:8000"

  travelci-gateway:
    image: travelci/tci-gateway:latest
    networks:
      - spring-cloud-network
    ports:
      - "${TCI_ZUUL_PORT}:8001"

  travelci-webhook:
    image: travelci/tci-webhook:latest
    networks:
      - spring-cloud-network
  
  travelci-projects:
    image: travelci/tci-projects:latest
    networks:
      - spring-cloud-network
      - bdd-network
    volumes:
      - tci-projects-volume:/usr/app/travel-ci

  travelci-projects2:
    image: travelci/tci-projects:latest
    networks:
      - spring-cloud-network
      - bdd-network
    volumes:
      - tci-projects-volume:/usr/app/travel-ci

  travelci-commands:
    image: travelci/tci-commands:latest
    networks:
      - spring-cloud-network
      - bdd-network

  travelci-docker-runner:
    image: travelci/tci-docker-runner:latest
    networks:
      - spring-cloud-network
    volumes:
      - tci-projects-volume:/usr/app/travel-ci

  travelci-logger:
    image: travelci/tci-logger:latest
    networks:
      - spring-cloud-network
      - bdd-network

  travelci-notifications:
    image: travelci/tci-notifications:latest
    networks:
      - spring-cloud-network

  travelci-webapp:
    image: travelci/tci-webapp:latest
    ports:
      - "${TCI_WEBAPP_PORT}:80"