version: '3'

networks:
  spring-cloud-network:
  bdd-network:

volumes:
  tci-database-volume:

services:
  travelci-database:
    image: travelci/tci-database:latest
    networks:
      - bdd-network
    volumes:
      - tci-database-volume:/var/lib/postgresql/data

  travelci-config:
    image: travelci/tci-config:latest
    networks:
      - spring-cloud-network
    ports:
      - "${TCI-CONFIG-PORT}:8888"

  travelci-eureka:
    image: travelci/tci-eureka:latest
    networks:
      - spring-cloud-network
    ports:
      - "${TCI-EUREKA-PORT}:8000"

  travelci-zuul:
    image: travelci/tci-zuul:latest
    networks:
      - spring-cloud-network
    ports:
      - "${TCI-ZUUL-PORT}:8001"

  travelci-webhook:
    image: travelci/tci-webhook:latest
    networks:
      - spring-cloud-network
    ports:
      - "${TCI-WEBHOOK-PORT}:8080"